language: node_js
sudo: false

cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache

node_js:
  - "5"
  - "4"

install:
  - npm install yarn -g
  - yarn install

before_script:
 - chmod +x .config/webpack.build.js

script:
- npm run lint

branches:
  only:
  - master
