language: node_js
sudo: false
dist: trusty
cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
node_js:
  - "6"

before_install:
  - npm i -g yarn --cache-min 999999999
  - "export CHROME_BIN=/usr/bin/google-chrome"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - yarn

script:
- yarn lint
- yarn test
- yarn bundlesize
- yarn build:demo

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && yarn gh-pages

branches:
  only:
  - next

addons:
  apt:
    packages:
      - google-chrome-stable

env:
  global:
    secure: GywEi6rCdMo68c+2aSxF31yAtciDWgQ4A++zUXKXqFFlMRrzsSlgo0+US+eT/+Kaz5CZIXIKJiWRmbPdhgJKs1rkVE7CJiZokdDdgfoEy8xAmlMhjbYN44Y0j5S9bIlhwqR9kW9kNg2sj5/Kv88bjSXehmT+RdOFfGN5gkxTzhs=
