language: node_js
sudo: false
dist: trusty
cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
node_js:
  - "6"

before_install:
  - npm i -g yarn --cache-min 999999999
  - "export CHROME_BIN=/usr/bin/google-chrome"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - yarn

script:
- yarn lint
- yarn test

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
  - master

addons:
  apt:
    packages:
      - google-chrome-stable
