language: node_js
sudo: false

node_js:
  - "5"
  - "4"

before_install:
- npm install -g npm@latest

before_script:
 - chmod +x .config/webpack.build.js

script:
- npm run flow.compile

branches:
  only:
  - master

cache:
  directories:
    - node_modules
