language: node_js
sudo: false

cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
node_js:
  - "6"

before_install:
  - npm i -g yarn --cache-min 999999999

install:
  - yarn

before_script:
  - node node_modules/phantomjs-prebuilt/install.js

script:
- yarn lint
- yarn test

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
  - master
